version: '3.9'
services:
  apache:
    image: httpd:2.2
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./conf:/usr/local/apache2/conf